export const token =
  'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0NzBkMjIwNmMzYTc1MzM4YzllZjc0M2UxM2IzYjJjNSIsInN1YiI6IjVkODllZjNlNmMxZTA0MDAyMWFiZWUyMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.gpKHhxE6yHWr7SnzZ4x_1mIBvRgps4fq-sz_luRbVN4'
